// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package tipc

import "strconv"

const _EventType_name = "PublishedWithdrawnTimeout"

var _EventType_index = [...]uint8{0, 9, 18, 25}

func (i EventType) String() string {
	i -= 1
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
